### ISSUE TITLE
Scoped CSS 的 descendant, child selectors 优先级

### ISSUE THREAD

**Issue by junmer** [ecomfe/san-loader#7]
## 输入
```html
<style scoped>
.a .b .c {
    color: red
}
</style>
```

### 1.  向下兼容
```css
.a[913ce72] .b .c {
    color: red
}
```
场景： `slot` 与 第三方库
```
.container[913ce72] .slick-list {}
```

### 2. 向上兼容 
```css
.a .b .c[913ce72] {
    color: red
}
```
场景：全局主题
```
.theme-blue .button[913ce72] {}
```

## 问题

**1** 和 **2** 需要做一个选择, 收集大家的建议

或者，有更优的方案？
